  # 配置数据源
spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://10.9.53.57:3306/Yangtze?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
#    username: yangtze1
#    password: c8f2Mj1MGN
  datasource:
    url: jdbc:dm://10.10.10.236:5236/Yangtzedb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: SYSDBA
    password: Cttic@Dma@220811
    driver-class-name: dm.jdbc.driver.DmDriver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 9001
mybatis-plus:
  global-config:
    db-config:
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      updateStrategy: 1
